env:
  CIRRUS_CLONE_DEPTH: "1"

freebsd_instance:
  image_family: freebsd-12-1-snap

task:
  install_script: |
    pkg install -y git go
    GOBIN=$PWD/bin go get golang.org/dl/go1.16.6
    bin/go1.16.6 download
  build_script: bin/go1.16.6 build -v ./...
  test_script: bin/go1.16.6 test -race -v ./...
