# FIXME parameterize Go version in actions/cache key
name: main
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-latest
        - ubuntu-18.04
        - windows-latest
    env:
      AGE_VERSION: v1.0.0-rc.1
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.2
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache Go modules
      uses: actions/cache@v2.1.5
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go1.16.2-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go1.16.2-
    - name: Build
      run: |
        go build ./...
    - name: Run
      run: |
        go run . --version
    - name: Install age (Linux/macOS)
      if: runner.os == 'Linux' || runner.os == 'macOS' # FIXME add Windows
      run: |
        cd $(mktemp -d)
        goos=$(uname -s | tr '[:upper:]' '[:lower:]')
        curl -fsSL https://github.com/FiloSottile/age/releases/download/${AGE_VERSION}/age-${AGE_VERSION}-${goos}-amd64.tar.gz | tar xzf -
        sudo install -m 755 age/age /usr/local/bin
        sudo install -m 755 age/age-keygen /usr/local/bin
    - name: Install gpg4win (Windows)
      if: runner.os == 'Windows'
      run: |
        $env:PATH = "C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin"
        [Environment]::SetEnvironmentVariable("Path", $env:PATH, "Machine")
        choco install --yes gpg4win
        echo "C:\Program Files (x86)\GnuPG\bin" >> $env:GITHUB_PATH
    - name: Test
      run: go test -race ./...
  test-release:
    runs-on: ubuntu-18.04
    steps:
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get -yq --no-install-suggests --no-install-recommends install musl-tools snapcraft
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.2
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache Go modules
      uses: actions/cache@v2.1.5
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go1.16.2-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go1.16.2-
    - name: Build release
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --skip-publish --snapshot
    - name: Test release
      run: |
        # verify that version information is embedded correctly
        file ./dist/chezmoi-cgo-glibc_linux_amd64/chezmoi | tee /dev/stderr | grep -q "dynamically linked"
        file ./dist/chezmoi-cgo-musl_linux_amd64/chezmoi | tee /dev/stderr | grep -q "statically linked"
        ./dist/chezmoi-cgo-glibc_linux_amd64/chezmoi --version | tee /dev/stderr | grep -q "chezmoi version v2"
        ./dist/chezmoi-cgo-musl_linux_amd64/chezmoi --version | tee /dev/stderr | grep -q "chezmoi version v2"
        ./dist/chezmoi-nocgo_linux_386/chezmoi --version | tee /dev/stderr | grep -q "chezmoi version v2"
    - name: Upload artifact chezmoi-linux-amd64
      uses: actions/upload-artifact@v2
      with:
        name: chezmoi-linux-amd64
        path: dist/chezmoi-cgo-glibc_linux_amd64/chezmoi
    - name: Upload artifact chezmoi-linux-musl-amd64
      uses: actions/upload-artifact@v2
      with:
        name: chezmoi-linux-musl-amd64
        path: dist/chezmoi-cgo-musl_linux_amd64/chezmoi
    - name: Upload artifact chezmoi-darwin-amd64
      uses: actions/upload-artifact@v2
      with:
        name: chezmoi-darwin-amd64
        path: dist/chezmoi-nocgo_darwin_amd64/chezmoi
    - name: Upload artifact chezmoi-darwin-arm64
      uses: actions/upload-artifact@v2
      with:
        name: chezmoi-darwin-arm64
        path: dist/chezmoi-nocgo_darwin_arm64/chezmoi
    - name: Upload artifact chezmoi-windows-amd64
      uses: actions/upload-artifact@v2
      with:
        name: chezmoi-windows-amd64
        path: dist/chezmoi-nocgo_windows_amd64/chezmoi.exe
  generate:
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.2
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache Go modules
      uses: actions/cache@v2.1.5
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go1.16.2-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go1.16.2-
    - name: Generate
      run: |
        make completions
        git diff --exit-code
  lint:
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.2
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache Go modules
      uses: actions/cache@v2.1.5
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go1.16.2-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go1.16.2-
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.38.0
    - name: ShellCheck
      uses: ludeeus/action-shellcheck@1.0.0
      with:
        scandir: ./assets/scripts
    - name: Whitespace
      run:
        go run ./internal/cmd/lint-whitespace
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - generate
    - lint
    - test
    - test-release
    runs-on: ubuntu-18.04
    steps:
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get -yq --no-install-suggests --no-install-recommends install musl-tools snapcraft
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.2
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache Go modules
      uses: actions/cache@v2.1.5
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go1.16.2-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go1.16.2-
    - name: Snapcraft login
      env:
        SNAPCRAFT_LOGIN: ${{ secrets.SNAPCRAFT_LOGIN }}
      run: |
        snapcraft login --with <(echo "$SNAPCRAFT_LOGIN" | base64 -d)
    - name: Release
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
